### PR TITLE
Create 404 page

### PR DESCRIPTION
**Pull request by lerichardson**

### CODE REVIEW

**Comment by lerichardson** [comment]
I'm pretty sure there's some sort of node.js thing that needs to be added but I have little experience with node, so I'm not quite sure what.

**Comment by trevorthalacker** [comment]
Hey! Yes, this would need some work with node to add.
However, invalid links should be showing a 404 page already, generated using a Pug template (templates/404.pug)
If there is any URL that is showing a broken message (like "Cannot GET /"), please let me know, otherwise I see no reason to merge this.

**Comment by lerichardson** [comment]
Aha, I see. So if the folder name is unknown, **then** the `Cannot GET` page will show, e.g.:
image

**Comment by trevorthalacker** [comment]
I updated the UI (to fix some errors), as well as added the Express.js code

**Comment by lerichardson** [comment]
Sorry about those UI errors - I'm having some issues with VS Code, so I was editing it in the browser 😅

Get Outlook for Android<https://aka.ms/AAb9ysg>

________________________________

**Comment by trevorthalacker** [comment]
No problem, and thanks for letting me know this was a problem :)

**Pull request merged**
